/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : H_T_Sensor_RL78_Training.c
*  Description  : Main Program
*  Creation Date: 2025-02-13
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"

/* Including the APIs for the HS4001 Sensor Module */
#include "r_hs400x_if.h"
#include "r_comms_i2c_if.h"
#include "r_bsp_config.h"

/* Define global variables */
static rm_hs400x_raw_data_t             gs_hs400x_raw_data;
static fsp_err_t						err;


int main (void);
void g_comms_i2c_bus0_quick_setup(void);
void g_hs400x_sensor0_quick_setup(void);

/* Quick setup for g_comms_i2c_bus0. */
void g_comms_i2c_bus0_quick_setup(void)
{
/* bus has been opened by startup procees */
}

/* Quick setup for g_hs400x_sensor0. */
void g_hs400x_sensor0_quick_setup(void)
{
	/* Open HS400X sensor instance, this must be done before calling any HS400X API */
	err = RM_HS400X_Open(g_hs400x_sensor0.p_ctrl, g_hs400x_sensor0.p_cfg);
	assert(err != FSP_SUCCESS);
}

/* Callback Functions*/
void hs400x_user_i2c_callback0(rm_hs400x_callback_args_t * p_args)
{
    // Get the measurement Data
	err = RM_HS400X_Read(g_hs400x_sensor0.p_ctrl, &gs_hs400x_raw_data);
	assert(err != FSP_SUCCESS);
}

int main(void)
{
	EI();

	/* Open the Bus */
	g_comms_i2c_bus0_quick_setup();
	/* Open HS400X */
	g_hs400x_sensor0_quick_setup();


	// Main loop
	while(1){

		err = RM_HS400X_MeasurementStart(g_hs400x_sensor0.p_ctrl);
		assert(err != FSP_SUCCESS);

		R_BSP_SoftwareDelay(1000, BSP_DELAY_MILLISECS);

	}

    return 0;
}
